/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.loginus.vistas;
import com.mycompany.loginus.dao.*;
import com.mycompany.loginus.modelo.*;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.io.FileOutputStream;

import javax.swing.JFileChooser;

/**
 *
 * @author Luis Mendoza
 */
public class PanelUsuarios extends javax.swing.JFrame {
    private int idUsuario = -1;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PanelUsuarios.class.getName());

    /**
     * Creates new form PanelUsuarios
     */
    public PanelUsuarios() {
            initComponents();
            setLocationRelativeTo(null);
            setResizable(false);
            cargarUsuarios();
        }
    private void cargarUsuarios() {

        UsuarioDAO dao =
                new UsuarioDAO();

        ArrayList<Usuario> lista =
                dao.listar();

        DefaultTableModel modelo =
                new DefaultTableModel();

        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Usuario");
        modelo.addColumn("Correo");

        for(Usuario u : lista) {

            Object[] fila = {

                u.getId(),
                u.getNombre(),
                u.getApellido(),
                u.getUsuario(),
                u.getCorreo()

            };

            modelo.addRow(fila);

        }

        tablaUsuarios.setModel(modelo);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        btnExcel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Panel de Usuarios");

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Usuario", "Correo"
            }
        ));
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Usuario:");

        jLabel5.setText("Correo:");

        jLabel6.setText("Contraseña:");

        btnExcel.setText("Exportar Excel");
        btnExcel.addActionListener(this::btnExcelActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(btnEliminar))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtApellido)
                            .addComponent(txtUsuario)
                            .addComponent(txtCorreo)
                            .addComponent(txtNombre)
                            .addComponent(txtContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcel)
                        .addGap(51, 51, 51))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcel))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila =
                tablaUsuarios.getSelectedRow();

        if(fila == -1) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "SELECCIONE UN USUARIO"
            );

            return;

        }

        int id =
                Integer.parseInt(
                        tablaUsuarios
                        .getValueAt(fila, 0)
                        .toString()
                );

        UsuarioDAO dao =
                new UsuarioDAO();

        boolean eliminado =
                dao.eliminar(id);

        if(eliminado) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "USUARIO ELIMINADO"
            );

            cargarUsuarios();

        } else {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "ERROR AL ELIMINAR"
            );

        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
        int fila =
            tablaUsuarios.getSelectedRow();

        idUsuario =
                Integer.parseInt(
                        tablaUsuarios
                        .getValueAt(fila, 0)
                        .toString()
                );

        txtNombre.setText(
                tablaUsuarios
                .getValueAt(fila, 1)
                .toString()
        );

        txtApellido.setText(
                tablaUsuarios
                .getValueAt(fila, 2)
                .toString()
        );

        txtUsuario.setText(
                tablaUsuarios
                .getValueAt(fila, 3)
                .toString()
        );

        txtCorreo.setText(
                tablaUsuarios
                .getValueAt(fila, 4)
                .toString()
        );
    }//GEN-LAST:event_tablaUsuariosMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if(idUsuario == -1) {

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "SELECCIONE UN USUARIO"
                );

                return;

            }

            Usuario u = new Usuario();

            u.setId(idUsuario);

            u.setNombre(
                    txtNombre.getText()
            );

            u.setApellido(
                    txtApellido.getText()
            );

            u.setUsuario(
                    txtUsuario.getText()
            );

            u.setCorreo(
                    txtCorreo.getText()
            );

            u.setContraseña(
                    String.valueOf(
                            txtContraseña.getPassword()
                    )
            );

            UsuarioDAO dao =
                    new UsuarioDAO();

            boolean actualizado =
                    dao.actualizar(u);

            if(actualizado) {

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "USUARIO ACTUALIZADO"
                );

                cargarUsuarios();

            } else {

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "ERROR AL ACTUALIZAR"
                );

        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        try {

            XSSFWorkbook libro =
                    new XSSFWorkbook();

            XSSFSheet hoja =
                    libro.createSheet("Usuarios");

            // CABECERAS
            Row cabecera =
                    hoja.createRow(0);

            for(int i = 0;
                i < tablaUsuarios.getColumnCount();
                i++) {

                cabecera.createCell(i)
                        .setCellValue(
                                tablaUsuarios
                                .getColumnName(i)
                        );

            }

            // DATOS
            for(int i = 0;
                i < tablaUsuarios.getRowCount();
                i++) {

                Row fila =
                        hoja.createRow(i + 1);

                for(int j = 0;
                    j < tablaUsuarios.getColumnCount();
                    j++) {

                    Object valor =
                            tablaUsuarios
                            .getValueAt(i, j);

                    fila.createCell(j)
                            .setCellValue(
                                    valor.toString()
                            );

                }

            }

            JFileChooser chooser =
                    new JFileChooser();

            chooser.setSelectedFile(
                    new java.io.File(
                            "usuarios.xlsx"
                    )
            );

            int opcion =
                    chooser.showSaveDialog(this);

            if(opcion ==
                    JFileChooser.APPROVE_OPTION) {

                FileOutputStream archivo =
                        new FileOutputStream(
                                chooser
                                .getSelectedFile()
                        );

                libro.write(archivo);

                archivo.close();

                libro.close();

                javax.swing.JOptionPane
                        .showMessageDialog(
                                this,
                                "EXCEL EXPORTADO"
                        );

            }

        } catch (Exception e) {

            e.printStackTrace();

            javax.swing.JOptionPane
                    .showMessageDialog(
                            this,
                            "ERROR AL EXPORTAR"
                    );

        }
    }//GEN-LAST:event_btnExcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PanelUsuarios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnExcel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
